Feature/front  #5954845
digitalbutlers/arab-work pull request #1
Opened 2022-09-13 07:08 UTC by evgeniyNovicov

project ready for verification

2022-09-21 12:15 UTC, kirillsakun requested changes

2022-09-21 14:49 UTC, evgeniyNovicov commented on src/scripts/main.js
> +	function setTextPopup() {
set text popup => установить всплывающее окно с текстом

2022-09-21 14:51 UTC, evgeniyNovicov commented on src/scripts/main.js
> +			const logoName = targetLogo.querySelector('.logo-name');
я считаю что лучше использовать переменные, так код становится читабельнее

2022-09-21 14:53 UTC, evgeniyNovicov commented on src/scripts/main.js
> +			const popupCompanyTitles = document.querySelectorAll('.popup__title-company');
Я поменяю, но есть такое правило что главное слово обозначающее смысл переменной ставится последним, в этом случае, мы обращаемся к заголовкам а не к компаниям

2022-09-21 14:57 UTC, evgeniyNovicov commented on src/scripts/pages/index.js
> +	document.querySelector('.services__link-licensing').addEventListener('mouseover', () => cangeServicesImage('services__figure_licensing'));
это написанный код до меня, если у нас достаточно времени буду и его править

2022-09-21 15:10 UTC, evgeniyNovicov commented on src/styles/pages/home.scss
> +.hero__left-side{
это была бы переделка, класс уже существовал и поверь меня тоже с толку сбивал)

2022-09-22 08:01 UTC, evgeniyNovicov commented on src/scripts/main.js
> +			const arMonth = ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'];
Пока пропущу много время надо на переделку

2022-09-22 08:16 UTC, evgeniyNovicov commented on src/scripts/main.js
> +		const nextArrowClients = isRtl() ? '.swiper-clients__button-next' : '.swiper-clients__button-prev';
переименовал переменные, много завязано на этих классах, можно что-нибудь сломать

2022-09-22 08:22 UTC, evgeniyNovicov commented on src/scripts/main.js
> +			const popupButton = e.target.closest('[data-popupbutton]');
потому что e.target приходит внутренний элемент, а мне нужно брать значение атрибута родителя

2022-09-22 08:40 UTC, evgeniyNovicov commented on src/scripts/main.js
> +		if (popupButtons) {
проверил на длину

2022-09-22 08:42 UTC, evgeniyNovicov commented on src/scripts/main.js
> +			const targetLogo = e.target.closest('.clients__slide');
ок

2022-09-22 11:27 UTC, evgeniyNovicov commented on src/scripts/pages/news.js
> +				top: valueScroll,
Работает не корректно видимо из-за изменения высоты блока

2022-09-22 11:34 UTC, evgeniyNovicov commented on src/scripts/pages/about.js
> +		const prevArrowClients = isRtl() ? '.swiper-clients__button-prev' : '.swiper-clients__button-next';
это другой слайдер

2022-09-22 11:41 UTC, evgeniyNovicov commented on src/scripts/pages/article.js
> +		const prevArrowClients = isRtl() ? '.news-slider__arrow-left' : '.news-slider__arrow-right';
это другой слайдер, исправил название

2022-09-22 11:42 UTC, evgeniyNovicov commented on src/scripts/pages/article.js
> +		const newsClider = document.querySelector('.news-slider_wrapper');
такой слайдер один

2022-09-22 11:43 UTC, evgeniyNovicov commented on src/scripts/pages/contact.js
> +			if (e.target.closest('.form__radio')) {
не понял

2022-09-22 11:45 UTC, evgeniyNovicov commented on src/scripts/pages/contact.js
> +				selectItemINput.checked = true;
нужно проянить

2022-09-22 12:20 UTC, evgeniyNovicov commented on src/styles/mixins/colors.scss
> +@media screen and (prefers-color-scheme: light){
не стоит так делать, если что можем созвониться объясню

2022-09-22 12:46 UTC, evgeniyNovicov commented on src/styles/mixins/colors.scss
> +        background-size: 19px;
проверил, все же лучше другой картинкой

2022-09-22 14:18 UTC, evgeniyNovicov commented on src/scripts/main.js
> +			}, 300);
удалил оказался не нужен

2022-09-29 13:16 UTC, kirillsakun approved these changes

2022-09-29 13:16 UTC, kirillsakun approved these changes

2022-09-29 13:18 UTC, merged